"""create initial schema

Revision ID: 998d78be9c33
Revises: 
Create Date: 2026-09-28 21:13:29.073705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998d78be9c33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_categoria', sa.String(length=100), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('tbl_idioma',
    sa.Column('id_idioma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_idioma', sa.String(length=100), nullable=False),
    sa.Column('cd_idioma', sa.String(length=10), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_idioma'),
    sa.UniqueConstraint('cd_idioma', name='uq_tbl_idioma_cd_idioma')
    )
    op.create_table('tbl_usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_usuario', sa.String(length=50), nullable=False),
    sa.Column('ds_senha_hash', sa.String(length=255), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_idioma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_idioma'], ['tbl_idioma.id_idioma'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nm_usuario', name='uq_tbl_usuario_nm_usuario')
    )
    op.create_table('tbl_quiz',
    sa.Column('id_quiz', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_quiz', sa.Text(), nullable=False),
    sa.Column('ds_quiz', sa.Text(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_publico', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_ordem_aleatoria', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_distribuicao_automatica', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('nr_tempo_limite', sa.Integer(), nullable=True),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_publicacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_idioma', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            nr_tempo_limite IS NULL\n            OR nr_tempo_limite BETWEEN 1 AND 60\n            ', name='ck_tbl_quiz_nr_tempo_limite'),
    sa.ForeignKeyConstraint(['id_idioma'], ['tbl_idioma.id_idioma'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tbl_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_quiz')
    )
    op.create_table('tbl_arquivo',
    sa.Column('id_arquivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_arquivo', sa.String(length=255), nullable=False),
    sa.Column('uri_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tp_arquivo', sa.String(length=50), nullable=False),
    sa.Column('nr_questoes', sa.Integer(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.CheckConstraint('nr_questoes IS NULL OR nr_questoes > 0', name='ck_tbl_arquivo_nr_questoes'),
    sa.ForeignKeyConstraint(['id_quiz'], ['tbl_quiz.id_quiz'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('tbl_avaliacao',
    sa.Column('id_avaliacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nr_nota', sa.Integer(), nullable=False),
    sa.Column('dt_avaliacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.CheckConstraint('nr_nota BETWEEN 1 AND 5', name='ck_tbl_avaliacao_nr_nota'),
    sa.ForeignKeyConstraint(['id_quiz'], ['tbl_quiz.id_quiz'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tbl_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    op.create_table('tbl_pergunta',
    sa.Column('id_pergunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ds_pergunta', sa.Text(), nullable=False),
    sa.Column('nr_ordem', sa.Integer(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ds_explicacao', sa.Text(), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            is_ativo = false\n            OR nr_ordem IS NOT NULL\n            ', name='ck_tbl_pergunta_ordem_ativa'),
    sa.CheckConstraint('nr_ordem IS NULL OR nr_ordem > 0', name='ck_tbl_pergunta_nr_ordem_positiva'),
    sa.ForeignKeyConstraint(['id_quiz'], ['tbl_quiz.id_quiz'], ),
    sa.PrimaryKeyConstraint('id_pergunta')
    )
    op.create_index('uq_tbl_pergunta_quiz_nr_ordem_ativo', 'tbl_pergunta', ['id_quiz', 'nr_ordem'], unique=True, postgresql_where=sa.text('is_ativo = true'))
    op.create_table('tbl_quiz_categoria',
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['tbl_categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_quiz'], ['tbl_quiz.id_quiz'], ),
    sa.PrimaryKeyConstraint('id_quiz', 'id_categoria')
    )
    op.create_table('tbl_tentativa',
    sa.Column('id_tentativa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nr_questoes', sa.Integer(), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ds_status', sa.String(length=50), nullable=False),
    sa.CheckConstraint('nr_questoes > 0', name='ck_tbl_tentativa_nr_questoes'),
    sa.ForeignKeyConstraint(['id_quiz'], ['tbl_quiz.id_quiz'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tbl_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tentativa')
    )
    op.create_table('tbl_visualizacao',
    sa.Column('id_visualizacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt_visualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_visitante', sa.UUID(), nullable=True),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            (id_usuario IS NOT NULL AND id_visitante IS NULL)\n            OR\n            (id_usuario IS NULL AND id_visitante IS NOT NULL)\n            ', name='ck_tbl_visualizacao_usuario_visitante'),
    sa.ForeignKeyConstraint(['id_quiz'], ['tbl_quiz.id_quiz'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tbl_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_visualizacao')
    )
    op.create_index('ix_tbl_visualizacao_id_visitante', 'tbl_visualizacao', ['id_visitante'], unique=False)
    op.create_table('tbl_alternativa',
    sa.Column('id_alternativa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ds_alternativa', sa.Text(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_correto', sa.Boolean(), nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pergunta'], ['tbl_pergunta.id_pergunta'], ),
    sa.PrimaryKeyConstraint('id_alternativa')
    )
    op.create_index('uq_tbl_alternativa_pergunta_correta_ativa', 'tbl_alternativa', ['id_pergunta'], unique=True, postgresql_where=sa.text('is_ativo = true AND is_correto = true'))
    op.create_table('tbl_tentativa_pergunta',
    sa.Column('id_tentativa_pergunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tentativa', sa.Integer(), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.Column('nr_ordem', sa.Integer(), nullable=False),
    sa.CheckConstraint('nr_ordem > 0', name='ck_tbl_tentativa_pergunta_nr_ordem'),
    sa.ForeignKeyConstraint(['id_pergunta'], ['tbl_pergunta.id_pergunta'], ),
    sa.ForeignKeyConstraint(['id_tentativa'], ['tbl_tentativa.id_tentativa'], ),
    sa.PrimaryKeyConstraint('id_tentativa_pergunta'),
    sa.UniqueConstraint('id_tentativa', 'id_pergunta', name='uq_tbl_tentativa_pergunta_pergunta'),
    sa.UniqueConstraint('id_tentativa', 'nr_ordem', name='uq_tbl_tentativa_pergunta_ordem')
    )
    op.create_table('tbl_resposta',
    sa.Column('id_resposta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_alternativa', sa.Integer(), nullable=False),
    sa.Column('id_tentativa_pergunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_alternativa'], ['tbl_alternativa.id_alternativa'], ),
    sa.ForeignKeyConstraint(['id_tentativa_pergunta'], ['tbl_tentativa_pergunta.id_tentativa_pergunta'], ),
    sa.PrimaryKeyConstraint('id_resposta'),
    sa.UniqueConstraint('id_tentativa_pergunta', name='uq_tbl_resposta_tentativa_pergunta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_resposta')
    op.drop_table('tbl_tentativa_pergunta')
    op.drop_index('uq_tbl_alternativa_pergunta_correta_ativa', table_name='tbl_alternativa', postgresql_where=sa.text('is_ativo = true AND is_correto = true'))
    op.drop_table('tbl_alternativa')
    op.drop_index('ix_tbl_visualizacao_id_visitante', table_name='tbl_visualizacao')
    op.drop_table('tbl_visualizacao')
    op.drop_table('tbl_tentativa')
    op.drop_table('tbl_quiz_categoria')
    op.drop_index('uq_tbl_pergunta_quiz_nr_ordem_ativo', table_name='tbl_pergunta', postgresql_where=sa.text('is_ativo = true'))
    op.drop_table('tbl_pergunta')
    op.drop_table('tbl_avaliacao')
    op.drop_table('tbl_arquivo')
    op.drop_table('tbl_quiz')
    op.drop_table('tbl_usuario')
    op.drop_table('tbl_idioma')
    op.drop_table('tbl_categoria')
    # ### end Alembic commands ###
